/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function recognize(image: string | Buffer, options?: UniOcrOptions | undefined | null): Promise<RecognizeResult>

export interface RecognizeResult {
  text: string
  confidence: string
}

export interface UniOcrOptions {
  languages: Array<string>
  confidenceThreshold: number
  timeout: number
}
